In [2]:
import pandas as pd
import numpy as np
from fractions import Fraction

In [3]:
df = pd.read_csv('data_tennis.csv')
df.columns[0:-1]
df

# df = pd.read_csv('data_bool.csv')
# df

    O  T  H  w Play
0   S  H  H  W    N
1   S  H  H  S    N
2   O  H  H  W    Y
3   R  M  H  W    Y
4   R  C  N  W    Y
5   R  C  N  S    N
6   O  C  N  S    Y
7   S  M  H  W    N
8   S  C  N  W    Y
9   R  M  N  W    Y
10  S  M  N  S    Y
11  O  M  H  S    Y
12  O  H  N  W    Y
13  R  M  H  S    N

In [4]:
def entropy_calc_root(y):
    labels = dict(y.value_counts())
    sum = 0
    for v in labels.values():
        print('interfrac',Fraction(v,len(y)))
        sum = sum + -v/len(y)*np.log2(v/len(y))
    
    return(sum)

def expected_entropy(x,y):
    vals = dict(x.value_counts())
    sum = 0
    for k,v in vals.items():
        y_v = y.loc[x == k]
        print('Fraction #######',Fraction(v,len(x)),k)
        print('entropy:',entropy_calc_root(y_v),k)
        sum = sum+(v/len(x))*entropy_calc_root(y_v)
    return (sum) 

def info_gain(x,y):
    return(entropy_calc_root(y)-expected_entropy(x,y))


def info_gain_calc(df):
    d = dict()
    for c in df.columns[0:-1]:
        
        print('total=',expected_entropy(df[c],df.iloc[:,-1:]))
        d[c]= info_gain(df[c],df.iloc[:,-1:])
    return(d)


info_gain_calc(df)

Fraction ####### 5/14 S
interfrac 3/5
interfrac 2/5
entropy: 0.9709505944546686 S
interfrac 3/5
interfrac 2/5
Fraction ####### 5/14 R
interfrac 3/5
interfrac 2/5
entropy: 0.9709505944546686 R
interfrac 3/5
interfrac 2/5
Fraction ####### 2/7 O
interfrac 1
entropy: 0.0 O
interfrac 1
total= 0.6935361388961918
interfrac 9/14
interfrac 5/14
Fraction ####### 5/14 S
interfrac 3/5
interfrac 2/5
entropy: 0.9709505944546686 S
interfrac 3/5
interfrac 2/5
Fraction ####### 5/14 R
interfrac 3/5
interfrac 2/5
entropy: 0.9709505944546686 R
interfrac 3/5
interfrac 2/5
Fraction ####### 2/7 O
interfrac 1
entropy: 0.0 O
interfrac 1
Fraction ####### 3/7 M
interfrac 2/3
interfrac 1/3
entropy: 0.9182958340544896 M
interfrac 2/3
interfrac 1/3
Fraction ####### 2/7 H
interfrac 1/2
interfrac 1/2
entropy: 1.0 H
interfrac 1/2
interfrac 1/2
Fraction ####### 2/7 C
interfrac 3/4
interfrac 1/4
entropy: 0.8112781244591328 C
interfrac 3/4
interfrac 1/4
total= 0.9110633930116763
interfrac 9/14
interfrac 5/14
Fraction ####### 3/7 M
interfrac 2/3
interfrac 1/3
entropy: 0.9182958340544896 M
interfrac 2/3
interfrac 1/3
Fraction ####### 2/7 H
interfrac 1/2
interfrac 1/2
entropy: 1.0 H
interfrac 1/2
interfrac 1/2
Fraction ####### 2/7 C
interfrac 3/4
interfrac 1/4
entropy: 0.8112781244591328 C
interfrac 3/4
interfrac 1/4
Fraction ####### 1/2 H
interfrac 4/7
interfrac 3/7
entropy: 0.9852281360342515 H
interfrac 4/7
interfrac 3/7
Fraction ####### 1/2 N
interfrac 6/7
interfrac 1/7
entropy: 0.5916727785823275 N
interfrac 6/7
interfrac 1/7
total= 0.7884504573082896
interfrac 9/14
interfrac 5/14
Fraction ####### 1/2 H
interfrac 4/7
interfrac 3/7
entropy: 0.9852281360342515 H
interfrac 4/7
interfrac 3/7
Fraction ####### 1/2 N
interfrac 6/7
interfrac 1/7
entropy: 0.5916727785823275 N
interfrac 6/7
interfrac 1/7
Fraction ####### 4/7 W
interfrac 3/4
interfrac 1/4
entropy: 0.8112781244591328 W
interfrac 3/4
interfrac 1/4
Fraction ####### 3/7 S
interfrac 1/2
interfrac 1/2
entropy: 1.0 S
interfrac 1/2
interfrac 1/2
total= 0.8921589282623617
interfrac 9/14
interfrac 5/14
Fraction ####### 4/7 W
interfrac 3/4
interfrac 1/4
entropy: 0.8112781244591328 W
interfrac 3/4
interfrac 1/4
Fraction ####### 3/7 S
interfrac 1/2
interfrac 1/2
entropy: 1.0 S
interfrac 1/2
interfrac 1/2

{'O': 0.24674981977443933,
 'T': 0.02922256565895487,
 'H': 0.15183550136234159,
 'w': 0.04812703040826949}

In [189]:
(-(3/4)* np.log2(3/4) -(1/4)* np.log2(1/4))

0.8112781244591328

In [191]:
-(3/7)*0.918 - (4/7) * 0.811

-0.8568571428571428

In [156]:
entropy_calc_root(df['y'])

0.863120568566631

In [140]:
df_new = df[['T','H','w','Play']][df['O']=='O']
info_gain_calc(df_new)

0.0
0.0
0.0

{'T': 0.0, 'H': 0.0, 'w': 0.0}

In [235]:
def majority_error_root(y):
    labels = dict(y.value_counts())
    total = np.sum(list(labels.values()))
    most_common = max(labels.values())
    #print(Fraction((total-most_common),total))
    return((total-most_common)/total)

def expected_majority_error(x,y):
    vals = dict(x.value_counts())
    sum = 0
    for k,v in vals.items():
        y_v = y.loc[x == k]
        #print('Fraction #######',Fraction(v,len(x)),k)
        #print('me:',majority_error_root(y_v),k)
        sum = sum+(v/len(x))*majority_error_root(y_v)
    return (sum) 

def majority_gain(x,y):
    return(majority_error_root(y)-expected_majority_error(x,y))

def majority_gain_calc(df):
    d = dict()
    for c in df.columns[0:-1]:
        print(expected_majority_error(df[c],df.iloc[:,-1:]))
        d[c]= majority_gain(df[c],df.iloc[:,-1:])
    return(d)

majority_gain_calc(df)

0.28571428571428575
0.3571428571428571
0.2857142857142857
0.3571428571428571

{'O': 0.0714285714285714,
 'T': 5.551115123125783e-17,
 'H': 0.07142857142857145,
 'w': 5.551115123125783e-17}

In [5]:
def Gini_root(y):
    labels = dict(y.value_counts())
    sum = 0
    for v in labels.values():
        print(Fraction(v,len(y)))
        sum = sum + (v/len(y))**2
    
    return(1-sum)

def expected_GiniIndex(x,y):
    vals = dict(x.value_counts())
    sum = 0
    for k,v in vals.items():
        y_v = y.loc[x == k]
        print('Fraction #######',Fraction(v,len(x)),k)
        print('GI:',Gini_root(y_v),k)
        sum = sum+(v/len(x))*Gini_root(y_v)
    return (sum) 

def Gini_gain(x,y):
    return(Gini_root(y)-expected_GiniIndex(x,y))


def Gini_gain_calc(df):
    d = dict()
    for c in df.columns[0:-1]:
        
        print('vvv',expected_GiniIndex(df[c],df.iloc[:,-1:]))
        d[c]= Gini_gain(df[c],df.iloc[:,-1:])
    return(d)


df = pd.read_csv('data_tennis_outlook_sunny.csv')
#print(Gini_root(df['Play']))
Gini_gain_calc(df)

Fraction ####### 2/5 H
1
GI: 0.0 H
1
Fraction ####### 2/5 M
1/2
1/2
GI: 0.5 M
1/2
1/2
Fraction ####### 1/5 C
1
GI: 0.0 C
1
vvv 0.2
3/5
2/5
Fraction ####### 2/5 H
1
GI: 0.0 H
1
Fraction ####### 2/5 M
1/2
1/2
GI: 0.5 M
1/2
1/2
Fraction ####### 1/5 C
1
GI: 0.0 C
1
Fraction ####### 3/5 H
1
GI: 0.0 H
1
Fraction ####### 2/5 N
1
GI: 0.0 N
1
vvv 0.0
3/5
2/5
Fraction ####### 3/5 H
1
GI: 0.0 H
1
Fraction ####### 2/5 N
1
GI: 0.0 N
1
Fraction ####### 3/5 W
2/3
1/3
GI: 0.4444444444444444 W
2/3
1/3
Fraction ####### 2/5 S
1/2
1/2
GI: 0.5 S
1/2
1/2
vvv 0.4666666666666667
3/5
2/5
Fraction ####### 3/5 W
2/3
1/3
GI: 0.4444444444444444 W
2/3
1/3
Fraction ####### 2/5 S
1/2
1/2
GI: 0.5 S
1/2
1/2

{'T': 0.27999999999999997, 'H': 0.48, 'w': 0.013333333333333308}

In [237]:
def Gini_root(y):
    labels = dict(y.value_counts())
    sum = 0
    for v in labels.values():
        #print(Fraction(v,len(y)))
        sum = sum + (v/len(y))**2
    
    return(1-sum)

def expected_GiniIndex(x,y):
    vals = dict(x.value_counts())
    sum = 0
    for k,v in vals.items():
        y_v = y.loc[x == k]
        #print('Fraction #######',Fraction(v,len(x)),k)
        #print('GI:',Gini_root(y_v),k)
        sum = sum+(v/len(x))*Gini_root(y_v)
    return (sum) 

def Gini_gain(x,y):
    return(Gini_root(y)-expected_GiniIndex(x,y))


def Gini_gain_calc(df):
    d = dict()
    for c in df.columns[0:-1]:
        
        print(expected_GiniIndex(df[c],df.iloc[:,-1:]))
        d[c]= Gini_gain(df[c],df.iloc[:,-1:])
    return(d)


df = pd.read_csv('data_tennis_outlook_sunny.csv')
print(Gini_root(df['Play']))
Gini_gain_calc(df)

0.48
0.2
0.0
0.4666666666666667

{'T': 0.27999999999999997, 'H': 0.48, 'w': 0.013333333333333308}

## Q3 Missing with Outlook = Sunny

In [162]:
df_m = pd.read_csv('data_tennis_missing.csv')
df_m

    O  T  H  W Play
0   S  H  H  W    N
1   S  H  H  S    N
2   O  H  H  W    Y
3   R  M  H  W    Y
4   R  C  N  W    Y
5   R  C  N  S    N
6   O  C  N  S    Y
7   S  M  H  W    N
8   S  C  N  W    Y
9   R  M  N  W    Y
10  S  M  N  S    Y
11  O  M  H  S    Y
12  O  H  N  W    Y
13  R  M  H  S    N
14  S  M  N  W    Y

In [163]:
info_gain_calc(df_m)

0.7236501981515562
0.8857970985201966
0.7496741665224355
0.8585227039051722

{'O': 0.19464563590293338,
 'T': 0.032498735534292944,
 'H': 0.1686216675320541,
 'W': 0.0597731301493174}

In [164]:
0.918-0.749

0.16900000000000004

## Q3 Missing with Outlook = Rainy

In [145]:
df_r = pd.read_csv('data_tennis_missing_r.csv')
df_r

    O  T  H  W Play
0   S  H  H  W    N
1   S  H  H  S    N
2   O  H  H  W    Y
3   R  M  H  W    Y
4   R  C  N  W    Y
5   R  C  N  S    N
6   O  C  N  S    Y
7   S  M  H  W    N
8   S  C  N  W    Y
9   R  M  N  W    Y
10  S  M  N  S    Y
11  O  M  H  S    Y
12  O  H  N  W    Y
13  R  M  H  S    N
14  R  M  N  W    Y

In [148]:
info_gain_calc(df_r)

0.690968531773352
0.8857970985201966
0.7496741665224355
0.8585227039051722

{'O': 0.2273273022811375,
 'T': 0.032498735534292944,
 'H': 0.1686216675320541,
 'W': 0.0597731301493174}

# Q3 Missing outlook with second branch humidity = H

In [168]:
df_m_H = pd.read_csv('data_tennis_missing_humdity_H.csv')
df_m_H

   O  T  W Play
0  S  H  W    N
1  S  H  S    N
2  O  H  W    Y
3  R  M  W    Y
4  S  M  W    N
5  O  M  S    Y
6  R  M  S    N

In [166]:
info_gain_calc(df_m_H)

0.2857142857142857
0.9649839288804954
0.9649839288804954

{'O': 0.6995138503199658, 'T': 0.020244207153756077, 'W': 0.020244207153756077}

In [169]:
entropy_calc_root(df_m_H['Play'])

0.9852281360342515

In [170]:
2/7

0.2857142857142857